### ISSUE TITLE
include unsolicited messages

### ISSUE THREAD

**Issue by ewheeler** [rapidpro/tracpro#4]
Currently, tracpro only pulls messages that are in response to flows that have been designated as polls. 
In many cases, the supervisors that will be logging into tracpro to review these data are also the people who should be responding to queries from their reporting cohorts -- and these supervisors will not have access to rapidpro.

**Comment by rowanseymour** [comment]
@ewheeler now that /(Rapid)?Case(ly|Pro)?/ exists - does this change anything? It seems like it's not an exact fit because there's no way to segment users and contacts by Region (i.e. ContactGroup)... but it also seems a shame to have an existing system for handling unsolicited messages that we can't leverage.

**Comment by ewheeler** [comment]
@rowanseymour yeah i think this is definitely a topic for discussion with the upcoming  `/(Rapid)?Dash(ly|ing|Pro)?/` work portion we discussed in CPT as part of the next phase of work on `/(Rapid)?Track(ly|Pro)?/`

my inclination is that `/(Rapid)?Case(ly|Pro)?/` will fit the bill once these products are more cohesive in how they work together. but we certainly should think through whether these use-cases are different enough to justify independent implementations

cc @daaray @tobiasmcnulty @rebecca-caktus

**Comment by emullaney** [comment]
This was completed previously and is available in the `Inbox Messages` app.
